"""Self-tests for the frozen PPTX fixture-corpus convention."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from .unitutil.file import test_file_dir
from .unitutil.pptx_corpus import parse_manifest, sha256_file, validate_fixture_corpus

_CORPUS_ROOT = Path(test_file_dir) / "pptx" / "layout-cloning"


def test_frozen_repository_corpus_controls_are_valid():
    validate_fixture_corpus(_CORPUS_ROOT)


def test_repository_corpus_is_deliberately_empty_and_forbids_generated_ground_truth():
    manifest = (_CORPUS_ROOT / "MANIFEST.sha256").read_text(encoding="utf-8")
    readme = (_CORPUS_ROOT / "README.md").read_text(encoding="utf-8")

    assert manifest.splitlines() == ["# EMPTY: no fixture artifacts are committed yet."]
    assert "must not be generated by the production code under test" in " ".join(readme.split())


def test_empty_corpus_without_explicit_marker_is_rejected(tmp_path):
    corpus_root = tmp_path / "layout-cloning"
    corpus_root.mkdir()
    (corpus_root / "README.md").write_text("temporary convention", encoding="utf-8")
    (corpus_root / "MANIFEST.sha256").write_text("# merely blank\n", encoding="utf-8")

    with pytest.raises(AssertionError, match="empty corpus must contain"):
        validate_fixture_corpus(corpus_root)


def test_empty_corpus_marker_cannot_accompany_fixture_entries(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    manifest_path = corpus_root / "MANIFEST.sha256"
    manifest_path.write_text(
        "# EMPTY: no fixture artifacts are committed yet.\n"
        + manifest_path.read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    with pytest.raises(AssertionError, match="cannot accompany fixture entries"):
        validate_fixture_corpus(corpus_root)


def test_sha256_file_calculates_digest_from_file_bytes(tmp_path):
    path = tmp_path / "fixture.bin"
    path.write_bytes(b"frozen fixture")

    assert sha256_file(path) == hashlib.sha256(b"frozen fixture").hexdigest()


def test_manifest_parser_rejects_duplicate_paths(tmp_path):
    manifest = tmp_path / "MANIFEST.sha256"
    manifest.write_text(
        f"{'0' * 64}  powerpoint-authored/example.pptx\n"
        f"{'1' * 64}  powerpoint-authored/example.pptx\n",
        encoding="utf-8",
    )

    with pytest.raises(AssertionError, match="duplicate manifest path"):
        parse_manifest(manifest)


@pytest.mark.parametrize(
    "line",
    [
        "not-a-hash  powerpoint-authored/example.pptx",
        f"{'0' * 64} powerpoint-authored/example.pptx",
        f"{'A' * 64}  powerpoint-authored/example.pptx",
        f"{'0' * 64}  ../example.pptx",
    ],
)
def test_manifest_parser_rejects_malformed_lines_and_paths(tmp_path, line):
    manifest = tmp_path / "MANIFEST.sha256"
    manifest.write_text(f"{line}\n", encoding="utf-8")

    with pytest.raises(AssertionError):
        parse_manifest(manifest)


def test_populated_temporary_corpus_has_exact_manifest_pairing_and_valid_schemas(tmp_path):
    corpus_root = _populated_corpus(tmp_path)

    validate_fixture_corpus(corpus_root)


@pytest.mark.parametrize(
    "role", ["powerpoint-authored", "powerpoint-normalized", "synthetic-invalid"]
)
def test_all_fixture_categories_have_valid_temporary_examples(tmp_path, role):
    corpus_root = _populated_corpus(tmp_path, role=role)

    validate_fixture_corpus(corpus_root)


def test_missing_manifest_entry_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    manifest = parse_manifest(corpus_root / "MANIFEST.sha256")
    manifest.pop("powerpoint-authored/example.pptx")
    _write_manifest_entries(corpus_root, manifest)

    with pytest.raises(AssertionError, match="unlisted files") as error:
        validate_fixture_corpus(corpus_root)

    assert "powerpoint-authored/example.pptx" in str(error.value)


def test_manifest_entry_for_missing_file_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    manifest = parse_manifest(corpus_root / "MANIFEST.sha256")
    manifest["powerpoint-authored/missing.pptx"] = "0" * 64
    _write_manifest_entries(corpus_root, manifest)

    with pytest.raises(AssertionError, match="missing files") as error:
        validate_fixture_corpus(corpus_root)

    assert "powerpoint-authored/missing.pptx" in str(error.value)


def test_unlisted_corpus_file_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    (corpus_root / "powerpoint-authored" / "unlisted.json").write_text("{}")

    with pytest.raises(AssertionError, match="unlisted files"):
        validate_fixture_corpus(corpus_root)


def test_missing_fixture_sidecar_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    sidecar = corpus_root / "powerpoint-authored" / "example.json"
    sidecar.unlink()
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match="missing fixture sidecars"):
        validate_fixture_corpus(corpus_root)


def test_orphan_fixture_sidecar_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    orphan = corpus_root / "powerpoint-authored" / "orphan.json"
    orphan.write_text(json.dumps(_sidecar()), encoding="utf-8")
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match="orphan fixture sidecars"):
        validate_fixture_corpus(corpus_root)


def test_missing_desktop_verification_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    verification = corpus_root / "powerpoint-authored" / "example.desktop.json"
    verification.unlink()
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match="missing desktop verification"):
        validate_fixture_corpus(corpus_root)


def test_orphan_desktop_verification_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    orphan = corpus_root / "powerpoint-authored" / "orphan.desktop.json"
    orphan.write_text(json.dumps(_desktop_verification()), encoding="utf-8")
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match="orphan desktop verification"):
        validate_fixture_corpus(corpus_root)


@pytest.mark.parametrize(
    ("field_name", "value", "diagnostic"),
    [
        ("date", "2026-02-30", "date must be an ISO date"),
        ("role", "generated", "invalid fixture role"),
    ],
)
def test_invalid_fixture_sidecar_date_or_role_is_rejected(tmp_path, field_name, value, diagnostic):
    corpus_root = _populated_corpus(tmp_path)
    sidecar_path = corpus_root / "powerpoint-authored" / "example.json"
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar[field_name] = value
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match=diagnostic):
        validate_fixture_corpus(corpus_root)


def test_powerpoint_fixture_with_dishonest_application_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    sidecar_path = corpus_root / "powerpoint-authored" / "example.json"
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["application"] = "python-pptx"
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match="must name PowerPoint"):
        validate_fixture_corpus(corpus_root)


@pytest.mark.parametrize(
    ("mutation", "diagnostic"),
    [
        (lambda data: data.pop("source"), "missing required fields"),
        (lambda data: data.update(extra="unreviewed"), "unexpected fields"),
        (lambda data: data.update(description=""), "description must be a non-empty string"),
    ],
)
def test_malformed_fixture_sidecar_fields_are_rejected(tmp_path, mutation, diagnostic):
    corpus_root = _populated_corpus(tmp_path)
    sidecar_path = corpus_root / "powerpoint-authored" / "example.json"
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    mutation(sidecar)
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match=diagnostic):
        validate_fixture_corpus(corpus_root)


def test_invalid_fixture_sidecar_json_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    sidecar_path = corpus_root / "powerpoint-authored" / "example.json"
    sidecar_path.write_text("{", encoding="utf-8")
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match="invalid JSON"):
        validate_fixture_corpus(corpus_root)


def test_invalid_desktop_verification_status_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    verification_path = corpus_root / "powerpoint-authored" / "example.desktop.json"
    verification = json.loads(verification_path.read_text(encoding="utf-8"))
    verification["status"] = "maybe"
    verification_path.write_text(json.dumps(verification), encoding="utf-8")
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match="invalid desktop-verification status"):
        validate_fixture_corpus(corpus_root)


@pytest.mark.parametrize(
    ("field_name", "value", "diagnostic"),
    [
        ("date", "2026-02-30", "date must be an ISO date"),
        ("application", "LibreOffice", "must name PowerPoint"),
        ("version", "", "version must be a non-empty string"),
        ("platform", None, "platform must be a non-empty string"),
        ("notes", None, "notes must be a string"),
    ],
)
def test_invalid_completed_desktop_verification_fields_are_rejected(
    tmp_path, field_name, value, diagnostic
):
    corpus_root = _populated_corpus(tmp_path)
    verification_path = corpus_root / "powerpoint-authored" / "example.desktop.json"
    verification = json.loads(verification_path.read_text(encoding="utf-8"))
    verification[field_name] = value
    verification_path.write_text(json.dumps(verification), encoding="utf-8")
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match=diagnostic):
        validate_fixture_corpus(corpus_root)


def test_not_run_desktop_verification_requires_null_environment_fields(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    verification_path = corpus_root / "powerpoint-authored" / "example.desktop.json"
    verification = _desktop_verification(status="not-run")
    verification["platform"] = "Windows"
    verification_path.write_text(json.dumps(verification), encoding="utf-8")
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match="platform must be null"):
        validate_fixture_corpus(corpus_root)


def test_hash_mismatch_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    (corpus_root / "powerpoint-authored" / "example.pptx").write_bytes(b"changed")

    with pytest.raises(AssertionError, match="hash mismatch") as error:
        validate_fixture_corpus(corpus_root)

    assert "powerpoint-authored/example.pptx" in str(error.value)


@pytest.mark.parametrize(
    ("role", "scenario", "diagnostic"),
    [
        ("powerpoint-authored", "Bad_Name", "lowercase kebab-case"),
        ("unknown", "example", "must be directly under"),
    ],
)
def test_fixture_naming_and_bucket_conventions_are_enforced(tmp_path, role, scenario, diagnostic):
    corpus_root = _populated_corpus(tmp_path, role=role, scenario=scenario)

    with pytest.raises(AssertionError, match=diagnostic):
        validate_fixture_corpus(corpus_root)


def test_nested_fixture_directory_is_rejected(tmp_path):
    corpus_root = _populated_corpus(tmp_path)
    source = corpus_root / "powerpoint-authored"
    nested = source / "nested"
    nested.mkdir()
    for path in tuple(source.glob("example*")):
        path.rename(nested / path.name)
    _write_manifest(corpus_root)

    with pytest.raises(AssertionError, match="must be directly under"):
        validate_fixture_corpus(corpus_root)


def _populated_corpus(
    tmp_path: Path, *, role: str = "powerpoint-authored", scenario: str = "example"
) -> Path:
    corpus_root = tmp_path / "layout-cloning"
    fixture_directory = corpus_root / role
    fixture_directory.mkdir(parents=True)
    (corpus_root / "README.md").write_text("temporary convention", encoding="utf-8")
    (fixture_directory / f"{scenario}.pptx").write_bytes(b"temporary PPTX stand-in")
    (fixture_directory / f"{scenario}.json").write_text(
        json.dumps(_sidecar(role=role)), encoding="utf-8"
    )
    (fixture_directory / f"{scenario}.desktop.json").write_text(
        json.dumps(
            _desktop_verification(status="not-run" if role == "synthetic-invalid" else "passed")
        ),
        encoding="utf-8",
    )
    _write_manifest(corpus_root)
    return corpus_root


def _sidecar(*, role: str = "powerpoint-authored") -> dict[str, object]:
    return {
        "schema_version": 1,
        "role": role,
        "date": "2026-07-21",
        "description": "Temporary package for corpus-validator self-tests.",
        "source": "Created from scratch for this test.",
        "application": None if role == "synthetic-invalid" else "Microsoft PowerPoint",
    }


def _desktop_verification(*, status: str = "passed") -> dict[str, object]:
    completed = status != "not-run"
    return {
        "schema_version": 1,
        "status": status,
        "date": "2026-07-21" if completed else None,
        "application": "Microsoft PowerPoint" if completed else None,
        "version": "test-version" if completed else None,
        "platform": "test-platform" if completed else None,
        "notes": "Temporary validator self-test.",
    }


def _write_manifest(corpus_root: Path) -> None:
    entries = {
        path.relative_to(corpus_root).as_posix(): sha256_file(path)
        for path in corpus_root.rglob("*")
        if path.is_file() and path.name not in {"MANIFEST.sha256", "README.md"}
    }
    _write_manifest_entries(corpus_root, entries)


def _write_manifest_entries(corpus_root: Path, entries: dict[str, str]) -> None:
    lines = [f"{digest}  {path}\n" for path, digest in sorted(entries.items())]
    (corpus_root / "MANIFEST.sha256").write_text("".join(lines), encoding="utf-8")
